name: logging_utils
description: A package for logging with more extensive options than the built in logger.
version: 1.0.0
repository: https://github.com/davidgmolnar-pub-dev/logging_utils
issue_tracker: https://github.com/davidgmolnar-pub-dev/logging_utils/issues

topics:
  - debugging
  - logging

environment:
  sdk: ^3.2.5

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
